apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-balbalm-walk
  namespace: devocean
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: balbalm-walk
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: balbalm-walk
    spec:
      containers:
      - env:
        - name: project
          value: devocean
        image: 147997130241.dkr.ecr.ap-northeast-2.amazonaws.com/balbalm/backend-walk:0.0.1
        imagePullPolicy: Always
        name: balbalm-walk
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 2Gi
            memory: 512Mi
          requests:
            cpu: 250m
            ephemeral-storage: 2Gi
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30